# Generated by Django 6.0 on 2025-12-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(default=399)),
                ('rating', models.FloatField(default=4.6)),
                ('rating_count', models.IntegerField(default=1063)),
                ('category', models.CharField(choices=[('Generative AI', 'Generative AI'), ('IT Certifications', 'IT Certifications'), ('Data Science', 'Data Science'), ('DevOps', 'DevOps'), ('Web Development', 'Web Development')], default='Generative AI', max_length=64)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
