# Generated by Django 6.0 on 2025-12-26 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_review_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='courses_rev_rating_004eae_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['course'], name='courses_rev_course__8906ec_idx'),
        ),
    ]
